debug: true

spring:
  profiles:
    active: h2
    default: h2

  #throw an exception when it can’t find a handler for a particular URL
  mvc:
    throw-exception-if-no-handler-found: true
# Disable the default mappings
  resources:
    :add-mappings: false
server:
  port: 8082
  error:
    whitelabel:
      enabled: true  # Whether to enable the default error page displayed in browsers in case of a server error.

log4j:
  logger:
    org:
      hibernate:
        type: trace

logging:
  level:
    org:
      springframework:
        web : DEBUG
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

google:
  client:
    clientId : 729817514724-7jp1jis81fiuk4pvkiqc5nk2kspqev22.apps.googleusercontent.com
    clientSecret : ${LT_SECRET}
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile email https://www.googleapis.com/auth/contacts
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
    preferTokenInfo: false
  people:
    api:
      write:
        limit: 30

## make the JavaScript components provided by Angular available anonymously to the application


security:
  ignored : "*.bundle.*"
