spring:
  main:
    allow-bean-definition-overriding: true
  profiles: work
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    initialization-mode: always
    url: jdbc:oracle:thin:@localhost:1521:xe   # Datasource note use jdbc-url for multiple dbs
    username: local
    password: ${ORA_PWD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

secondDB:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url : jdbc:postgresql://localhost/trvanskeddb
    username : postgres
    password : ${PSQL_PWD}



security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'


