
spring:
  profiles:
    active: h2
    default: h2

  #throw an exception when it can’t find a handler for a particular URL
  mvc:
    throw-exception-if-no-handler-found: true
# Disable the default mappings
  resources:
    :add-mappings: false
server:
  error:
    whitelabel:
      enabled: true  # Whether to enable the default error page displayed in browsers in case of a server error.
